In [2]:
import pandas as pd, numpy as np
import sys, os
from pprint import pprint
import random
from datetime import datetime, timedelta

# Index
1. [Loop](#loop)
2. [Sorting](#sort)
3. [Searching](#search)
4. [Regular Expression](#regex)
8. [Lambda, Map, Reduce, Filter](#lambda)

In [3]:
def print_runtime():
    print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    print("-"*19)
print_runtime()

2021-07-01 17:48:21
-------------------


# 1. Loop <a id="loop"/>

In [64]:
ls_number = np.random.randint(0, 20, size=10)

In [65]:
pprint(ls_number)

array([ 5,  1,  7, 11, 11,  4, 14,  2, 10, 16])


In [11]:
max_value = max(ls_number)
min_value = min(ls_number)
total = sum(ls_number)
print(max_value, min_value, total)

199 72 2449


In [12]:
n = 6
for i in range(1, n):
    my_str = ""
    for j in range(1, i):
        my_str += str(j) + " "
    print(my_str)


1 
1 2 
1 2 3 
1 2 3 4 


In [13]:
n = 4
n = 6
i, j = 0, 0
for i in range(1, n+1):
    print(i, j, end=": ")
    for j in range(1, i+1):
        c_j_i = 1 #i!/j!(i-j)!
        for k in range(1, i-j+1):
            c_j_i *= (k + j - 2)/k
        print(int(c_j_i), end = " ")
    print()

1 0: 1 
2 1: 0 1 
3 2: 0 1 1 
4 3: 0 1 2 1 
5 4: 0 1 3 3 1 
6 5: 0 1 4 6 4 1 


In [14]:
ls_prev = [0, 1, 1]
n = 6
pprint(ls_prev[1:])
for _ in range(0, n):
    ls_now = [0]
    for i in range(1, len(ls_prev)):
        ls_now.append(ls_prev[i] + ls_prev[i-1])
    ls_now.append(1)
    pprint(ls_now[1:])
    ls_prev = ls_now


[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]
[1, 6, 15, 20, 15, 6, 1]
[1, 7, 21, 35, 35, 21, 7, 1]


# 2. Sorting <a id="sort"/>

## 2.1 Selection Sort 

In [66]:
ls_number

array([ 5,  1,  7, 11, 11,  4, 14,  2, 10, 16])

In [67]:
ls_tmp = ls_number.copy()

In [68]:
print("Before sorting")
pprint(ls_tmp)

Before sorting
array([ 5,  1,  7, 11, 11,  4, 14,  2, 10, 16])


In [69]:
n = len(ls_tmp)
for i in range(0, n-1):  # i: 0 -> n-2              [...] X
    print(f"# {i}")
    for j in range(n-1, i, -1): # j: n-1 -> i+1     i [... X]
        if ls_tmp[j-1] > ls_tmp[j]:  
            # i=0: Last iterate ls_tmp[1-1] vs. ls_tmp[1]
            # print(f"Swap {j-1} {j}")
            tmp = ls_tmp[j-1]
            ls_tmp[j-1] = ls_tmp[j]
            ls_tmp[j] = tmp
print(ls_tmp)

# 0
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
[ 1  2  4  5  7 10 11 11 14 16]


In [ ]:
O(n^2)
O(n*logn)

In [39]:
print(ls_tmp)

[5 4 0 7 7]


## 2.2 Insertion Sort

## 2.3 Bubble Sort

### --------

# 3. Searching <a id="search"/>

In [70]:
ls_tmp

array([ 1,  2,  4,  5,  7, 10, 11, 11, 14, 16])

In [58]:
# Linear Search
a = 6
found = False
for i in range(0, n):
    if ls_tmp[i] == a:
        print(f"Found at {i}")
        found = True
if not found:
    print("Not found")
    
# O(n)

Not found


In [72]:
ls_tmp

array([ 1,  2,  4,  5,  7, 10, 11, 11, 14, 16])

In [76]:
# O(logn) - Binary Search
a = 11
found = False
b, e = 0, n-1  # Begin, end
idx = 0
while b <= e:
    print(f"# {idx}")
    i = (b + e)//2
    if a == ls_tmp[i]:
        found = True
        print(f"Found at {i}")
        break
    elif a < ls_tmp[i]:
        e = i - 1
    elif a > ls_tmp[i]:
        b = i + 1
    print(ls_tmp[b:e+1])
    idx += 1
        
if not found:
    print("Not found")

# 0
[10 11 11 14 16]
# 1
Found at 7


In [74]:
(0+3)//2

1

In [75]:
5//3

1

# 4. Regular Expression <a id="regex"/>

In [77]:
os.getcwd()

'/Users/newuser/Work/MyGithub/TestGit/Python'

In [79]:
os.path.join("a", "b")

'a/b'

In [80]:
'a' + '/' + 'b'

'a/b'

In [ ]:
/data # /resource -> .csv .pickle 
DEFAULT_PATH 

# 5. Recursive

In [81]:
# Fibonacci
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)
    
print(fibonacci(5))

5


In [ ]:
0 1 1 2 3 5 8 13 ...


In [82]:
2000 * 30

60000

# 6. Challenge Magic Square

In [84]:
#
# Complete the 'formingMagicSquare' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY s as parameter.
#

def formingMagicSquare(s):
    # Write your code here
    # 4 magic squares rotated
    ls_magic_sq = [
        [[8, 3, 4], 
         [1, 5, 9], 
         [6, 7, 2]],
        [[6, 1, 8], 
         [7, 5, 3], 
         [2, 9, 4]],
        [[2, 7, 6], 
         [9, 5, 1], 
         [4, 3, 8]],
        [[4, 9, 2], 
         [3, 5, 7], 
         [8, 1, 6]],
        [[4, 3, 8], 
         [9, 5, 1], 
         [2, 7, 6]],
        [[8, 1, 6], 
         [3, 5, 7], 
         [4, 9, 2]],
        [[6, 7, 2], 
         [1, 5, 9], 
         [8, 3, 4]],
        [[2, 9, 4], 
         [7, 5, 3], 
         [6, 1, 8]],
    ]
    min_cost = 45
    
    for sq in ls_magic_sq:
        print(sq)
        cost = 0
        for i, row in enumerate(sq):
            for j, col in enumerate(row):
                cost += abs(col - s[i][j])
        if min_cost > cost:
            min_cost = cost
        print(cost, min_cost)
        
    return min_cost

print_runtime()

2021-06-24 16:16:15
-------------------


# 7. GearVN Data

In [85]:
source_path = "./data/gearvn_1day.csv"
pdf_gearvn = pd.read_csv(source_path)
print(pdf_gearvn.shape)
display(pdf_gearvn.head(10))
print_runtime()

(1505, 28)


ID tích hợp            Thời gian  Tháng      Kho lấy hàng   Thành phố  \
0    hd226477  2021-03-05 21:57:14      3  2 HCM-HHT-KD-V.2  Bình Dương   
1    hd226472  2021-03-05 21:54:51      3       8 HCM-CQ-KD         NaN   
2    hd226472  2021-03-05 21:54:51      3       8 HCM-CQ-KD         NaN   
3    hd226472  2021-03-05 21:54:51      3       8 HCM-CQ-KD         NaN   
4    hd226472  2021-03-05 21:54:51      3       8 HCM-CQ-KD         NaN   
5    hd226472  2021-03-05 21:54:51      3       8 HCM-CQ-KD         NaN   
6    hd226475  2021-03-05 21:54:47      3  2 HCM-HHT-KD-V.2     Long An   
7    hd226475  2021-03-05 21:54:47      3  2 HCM-HHT-KD-V.2     Long An   
8    hd226475  2021-03-05 21:54:47      3  2 HCM-HHT-KD-V.2     Long An   
9    hd226475  2021-03-05 21:54:47      3  2 HCM-HHT-KD-V.2     Long An   

              Quận huyện                    Mã sản phẩm Ngành      Hãng  \
0  Thành phố Thủ Dầu Một            MAN-HKC-NB27C2-GAME   MAN       HKC   
1                    NaN       LAP-MSI-GF63-9SCSR-829VN   LAP       MSI   
2                    NaN              CHU-DAR-LM115G-BK   CHU     DAREU   
3                    NaN            TUI-GEARVN-SHOCK-15   TUI    GEARVN   
4                    NaN    RAM-LEX-CL22-8G-2666-SODIMM   RAM     LEXAR   
5                    NaN                   TAI-MSI-H991   TAI       MSI   
6          Huyện Đức Hòa  RAM-GSK-TRIDENTZ-1X8G-RGB3000   RAM   G.SKILL   
7          Huyện Đức Hòa  RAM-GSK-TRIDENTZ-1X8G-RGB3000   RAM   G.SKILL   
8          Huyện Đức Hòa               CPU-INT-i7-10700   CPU     INTEL   
9          Huyện Đức Hòa                  SSD-GIGA-240G   SSD  GIGABYTE   

  Mã chung      ...        Tổng thu  Ghi chú của CSKH    Trạng thái  \
0      NaN      ...         4790000               NaN  Hệ thống hủy   
1      NaN      ...        19940000          19940000  Hệ thống hủy   
2      NaN      ...        19940000               NaN  Hệ thống hủy   
3      NaN      ...        19940000               NaN  Hệ thống hủy   
4      NaN      ...        19940000               NaN  Hệ thống hủy   
5      NaN      ...        19940000               NaN  Hệ thống hủy   
6      NaN      ...        34330000          34330000  Hệ thống hủy   
7      NaN      ...        34330000               NaN  Hệ thống hủy   
8       i7      ...        34330000               NaN  Hệ thống hủy   
9      NaN      ...        34330000               NaN  Hệ thống hủy   

        Chăm sóc KH  Thiếu  Thieu  DH thiếu        Ngày xác nhận  \
0  Nguyễn Cao Thắng      0      0         0  2021-03-05 21:59:18   
1               NaN      0      0         0                  NaN   
2               NaN      0      0         0                  NaN   
3               NaN      0      0         0                  NaN   
4               NaN      0      0         0                  NaN   
5               NaN      0      0         0                  NaN   
6  Nguyễn Cao Thắng      0      0         0  2021-03-06 08:15:30   
7  Nguyễn Cao Thắng      0      0         0  2021-03-06 08:15:30   
8  Nguyễn Cao Thắng      0      0         0  2021-03-06 08:15:30   
9  Nguyễn Cao Thắng      0      0         0  2021-03-06 08:15:30   

   Thời gian xác nhận Nguồn đơn hàng  
0            0.001435          OTHER  
1            0.000000          OTHER  
2            0.000000          OTHER  
3            0.000000          OTHER  
4            0.000000          OTHER  
5            0.000000          OTHER  
6            0.431053          OTHER  
7            0.431053          OTHER  
8            0.431053          OTHER  
9            0.431053          OTHER  

[10 rows x 28 columns]

2021-06-25 16:08:48
-------------------


In [88]:
pdf_agent = pdf_gearvn[["Chăm sóc KH"]].drop_duplicates()
print(f"Number of agents: {pdf_agent.shape[0]}")
display(pdf_agent.head())

print_runtime()

Number of agents: 19


Chăm sóc KH
0   Nguyễn Cao Thắng
1                NaN
20       Võ Ngọc Hải
21     Võ Quốc Khánh
22  Nguyễn Minh Hiếu

2021-06-25 16:10:38
-------------------


In [89]:
pdf_prod = pdf_gearvn[["Ngành", "Hãng", "Mã sản phẩm", "Kho lấy hàng", "Giá"]].drop_duplicates()
print(f"Number of products: {pdf_prod.shape[0]}")
display(pdf_prod.head())

print_runtime()

Number of products: 714


Ngành    Hãng                  Mã sản phẩm      Kho lấy hàng       Giá
0   MAN     HKC          MAN-HKC-NB27C2-GAME  2 HCM-HHT-KD-V.2   5090000
1   LAP     MSI     LAP-MSI-GF63-9SCSR-829VN       8 HCM-CQ-KD  22990000
2   CHU   DAREU            CHU-DAR-LM115G-BK       8 HCM-CQ-KD    150000
3   TUI  GEARVN          TUI-GEARVN-SHOCK-15       8 HCM-CQ-KD         0
4   RAM   LEXAR  RAM-LEX-CL22-8G-2666-SODIMM       8 HCM-CQ-KD         0

2021-06-25 16:13:19
-------------------


In [95]:
# Product Code:
pdf_prod["Ngành"].unique()

array(['MAN', 'LAP', 'CHU', 'TUI', 'RAM', 'TAI', 'CPU', 'SSD', 'PW', 'VO',
       'TN', 'VGA', 'FAN', 'MB', 'KB', 'LC', 'TBM', 'BALO', 'LOA', 'GHE',
       'HDD', 'PK', 'TCG', 'PM', 'tai', 'CAM'], dtype=object)

In [ ]:
0 vs. "0"

In [92]:
pdf_order = pdf_gearvn[[
    "ID tích hợp", 
    "Thời gian", # Sales created order
    "Giá trị đơn hàng", "Tiền chiết khấu", "Tiền đặt cọc", "Tổng thu",
    "Ghi chú của CSKH", "Trạng thái", "Chăm sóc KH", "Thiếu", "Thieu", "DH thiếu", 
    "Ngày xác nhận", # Storage confirmed timestamp
    "Nguồn đơn hàng",
]].fillna("0").groupby(["ID tích hợp"], as_index=False).agg({
    "Thời gian": "max", 
    "Giá trị đơn hàng": "max", 
    "Tiền chiết khấu": "max", 
    "Tiền đặt cọc": "max", 
    "Tổng thu": "max",
    "Ghi chú của CSKH": "max", 
    "Trạng thái": "max", 
    "Chăm sóc KH": "max", 
    "Thiếu": "max", 
    "Thieu": "max", 
    "DH thiếu": "max", 
    "Ngày xác nhận": "max", 
    "Nguồn đơn hàng": "max"
})

print(f"Number of order: {pdf_order.shape[0]}")
display(pdf_order.head())

print_runtime()

Number of order: 556


ID tích hợp            Thời gian  Giá trị đơn hàng Tiền chiết khấu  \
0    hd222111  2021-03-05 10:22:28          16720000          520000   
1  hd223723-1  2021-03-05 14:11:09          23770000        1.13e+06   
2  hd223723-2  2021-03-05 15:28:33          23720000        1.08e+06   
3    hd223891  2021-03-05 15:03:45          23490000         5.5e+06   
4  hd224709-1  2021-03-05 10:05:24          16560000          890000   

  Tiền đặt cọc  Tổng thu Ghi chú của CSKH    Trạng thái        Chăm sóc KH  \
0            0  16720000                0  Hệ thống hủy    Nguyễn Thế Vinh   
1            0  23770000                0  Hệ thống hủy        Trần Anh Vũ   
2            0  23720000                0   Đã xác nhận  Nguyễn Hoàn Thiện   
3            0  23490000                0    Thành công  Nguyễn Đinh Thuận   
4            0  16560000        thieu LOA  Hệ thống hủy   Nguyễn Minh Hiếu   

   Thiếu  Thieu  DH thiếu        Ngày xác nhận Nguồn đơn hàng  
0      0      0         0                    0              0  
1      0      0         0  2021-03-05 14:15:47          OTHER  
2      0      0         0  2021-03-05 15:30:09          OTHER  
3      0      0         0  2021-03-06 07:58:59          OTHER  
4      0      1         1  2021-03-06 10:26:55          OTHER

2021-06-25 16:21:18
-------------------


In [93]:
pdf_order.shape

(556, 14)

# 8. Lambda functions <a id="lambda"/a>

#### I. Lambda function
- A lambda function is a small anonymous function.
- A lambda function can take any number of arguments, but can only have one expression.  
Syntax:
```
lambda arg0[, arg1, ...]: expression
```  
Example:
```
x = lambda a: a+10
print(x(5))
```

#### II. Map, Reduce, Filter  
- Apply on list
- Transform a list into another list
  + Map: Transforming elements
  + Filter: Choosing certain elements
  + Both  
  
Syntax:
```
filter(boolean_function, list)
map(transform_function, list)
reduce(aggregate_function, list)
```  
- Lambda functions are usually combined with map, reduce, filter functions

In [4]:
ls_number = np.random.randint(0, 20, size=10)

In [6]:
ls_number

array([ 5, 18, 13,  7, 11, 13, 15, 15, 14, 15])

In [5]:
def is_prime(element):
    if element == 2:
        return True
    elif element <= 1 or element % 2 == 0:
        return False
    else:
        for i in range(3, element, 2):
            if element % i == 0:
                return False
    return True
print_runtime()

2021-07-01 17:49:19
-------------------


In [9]:
ls_prime0 = [x for x in ls_number if is_prime(x)]
ls_prime1 = filter(is_prime, ls_number)
print(ls_prime0)
print(list(ls_prime1))
print_runtime()

[5, 13, 7, 11, 13]
[5, 13, 7, 11, 13]
2021-07-01 17:52:09
-------------------


In [10]:
# map function demo
def multiply_2(x):
    return x*2

ls_x2 = [x*2 for x in ls_number]
ls_x2_map = map(multiply_2, ls_number)
ls_x2_map_lambda = map(lambda x: x*2, ls_number)

print(ls_x2)
print(list(ls_x2_map))
print(list(ls_x2_map_lambda))
print_runtime()

[10, 36, 26, 14, 22, 26, 30, 30, 28, 30]
[10, 36, 26, 14, 22, 26, 30, 30, 28, 30]
[10, 36, 26, 14, 22, 26, 30, 30, 28, 30]
2021-07-01 17:54:12
-------------------


In [12]:
import functools

In [14]:
# reduce function demo
def cal(x, y):
    return x+y
sum_val = sum(ls_number)
sum_val_1 = functools.reduce(cal, ls_number)
sum_val_2 = functools.reduce(lambda x, y: x+y, ls_number)
print(sum_val, sum_val_1, sum_val_2)
print_runtime()

126 126 126
2021-07-01 17:57:17
-------------------


# 9. Files handling
#### I. Open/Close Files
- Open
  -  Syntax:
```
obj_file = open(file_name, mode)
```
Open mode:  
Read: 
`r, rb, r+, rb+`  
Write: 
`w, wb, w+, wb+`  
Append: 
`a, ab, a+, ab+`  

- Close:  
Syntax:
```
obj_file.close()
```

__Note__: Always close an opened file, otherwise the write method would not behavior correctly

Preferred method:
  ```
  with open(file_name, mode) as f:
      # Doing task
  ```
#### II. Read/Write
- Write:  
  - Syntax:
  ```
  obj_file.write(string)
  ```
- Read:
  - Syntax:
  ```
  output = obj_file.read(size)
  line = f.readline()
  ```
  
[Tutorialspoint](#https://www.tutorialspoint.com/python3/python_files_io.htm)  
[Python Docs](#https://docs.python.org/3/tutorial/inputoutput.html)

In [29]:
!cat data/example00.txt

Read file example
Read file example Read file example

In [30]:
# Demo: Open a file, read first line, append to that file
obj_file = open("data/example00.txt", "r+")
line = obj_file.readline()
new_line = "\n" + line + " " + line

obj_file.write(new_line)
obj_file.close()

In [31]:
!cat data/example00.txt

Read file example
Read file example Read file example
Read file example
 Read file example


In [32]:
!cat data/example01.txt

Read file example
The other exampleRead file example Read file example

In [33]:
# Demo: Open a file, read first line, swapcase, append to that file
with open("data/example01.txt", "r+") as obj_file:
    line = obj_file.readline()
    new_line = "\nThe other example" + line + " " + line

    obj_file.write(new_line)

In [34]:
!cat data/example01.txt

Read file example
The other exampleRead file example Read file example
The other exampleRead file example
 Read file example


In [ ]:
try:
    # Do sth
    assert(<Conditions>, "Error messages")
except ValueError as vex:
    # Do sth when error
    
except Exception as ex:
    # Do sth when error
    
finally:
    # After the try or except done!